### ISSUE TITLE
Finished Campaigns

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#101]
Zeplin: `Upcoming and Finished`

![Screenshot 2019-07-27 20 24 21](https://user-images.githubusercontent.com/15100667/61998798-5f86a080-b0ad-11e9-9072-b73a8a172e73.png)

Within the campaign view:
(Zeplin: `Campaign Finished`)

1) Top button
![Screenshot 2019-07-27 20 31 25](https://user-images.githubusercontent.com/15100667/61998811-83e27d00-b0ad-11e9-83ce-af3c9b896906.png)

2) Percentage Bar
![Screenshot 2019-07-27 20 32 14](https://user-images.githubusercontent.com/15100667/61998821-a1afe200-b0ad-11e9-91fd-1475a4add784.png)

3) Bottom button
![Screenshot 2019-07-27 20 32 38](https://user-images.githubusercontent.com/15100667/61998826-affdfe00-b0ad-11e9-8603-2190d82c3baa.png)

**Comment by sydneyitguy** [comment]
Finished status can be `running distributing sending_rewards completed`

Anything but `running` => make it finished @ggomaeng

**Comment by sydneyitguy** [comment]
![Uploading image.png…]()
