### ISSUE TITLE
Redirection after newly signed-up

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#102]
I think it's more natural to redirect to the main page when a new user newly signed-up rather than sending the person to the dashboard (Both a Hunter and a Maker). 

-- Hunter --
![redirection-2](https://user-images.githubusercontent.com/15100667/61998972-dc1a7e80-b0af-11e9-8eab-72b6b343d2e1.gif)

-- Maker --
![redirection-1](https://user-images.githubusercontent.com/15100667/61998974-e472b980-b0af-11e9-82bb-ae74f8d76ef6.gif)

**Comment by ggomaeng** [comment]
The users are redirected to home page after login as well. Let me know if you want that handled differently.
