### ISSUE TITLE
Default redirection may confuse makers when they create a campaign

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#104]
Whenever there's some unexpected error occurred during the campaign creation, Reviewhunt redirects to the empty campaign creation page as below.
It'd be better to send the draft page of the maker were working on.

![Screenshot 2019-07-27 21 19 07](https://user-images.githubusercontent.com/15100667/61999236-99a77080-b0b4-11e9-9ea7-2ec1f647665b.png)

**Comment by sydneyitguy** [comment]
"unexpected error occurred" can't be reproduced.
Please explain the steps in detail to reproduce the error.
