### ISSUE TITLE
Summarise the payment info that the maker input

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#105]
Please summarise the payment info that the maker chose in the bottom section of this page rather than the payment buttons are appear.

![Screenshot 2019-07-27 21 24 26](https://user-images.githubusercontent.com/15100667/61999271-25b99800-b0b5-11e9-905a-b78b2f781c47.png)

**Comment by ggomaeng** [comment]
Can @sydneyitguy add "currency" field to "campaigns/:id.json" api? There is no way for me to retrieve the currency method used right now.

**Comment by sydneyitguy** [comment]
Added `/campaigns/:id/payment.json` instead
