### ISSUE TITLE
Problem with payment

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#106]
1. The conversation rate is not correct
![Screenshot 2019-07-27 21 52 26](https://user-images.githubusercontent.com/15100667/61999445-d70dfd00-b0b8-11e9-940d-48704e20952a.png)

2. We should collect some identifiable information for KRW and Crypto payment so that we can match the transaction.
(ex_ 입금자명 for KRW, sender's address for crypto pay)

**Comment by sydneyitguy** [comment]
@cyh76507707 
To clarify,
1. how much did you set for bounty_total?
2. what is the campaign ID you created?

@ggomaeng 
Let's remove ".00" on KRW unit.
This is what backend use for currency decimals
```
self.amount = case currency
    when 'KRW'
      amount.round
    when 'USD'
      amount.round(2)
    when 'STEEM', 'HUNT'
      amount.round(3)
    else
      amount.round(8)
    end
```

Also, please add `depositor_name` and `depositor_phone` when it's KRW payment
![image](https://user-images.githubusercontent.com/1332279/62002521-c5703800-b140-11e9-9912-e6f37b8ab7ca.png)

**Comment by sydneyitguy** [comment]
@ggomaeng I just updated `/campaigns/:id/set_currency.json` API so it will output all detailed calculations like:

```
{
    "paid_at": null,
    "currency": "USD",
    "payment_info": {
        "depositor_name": "김두둥",
        "depositor_phone": "+821012341234"
    },
    "campaign_id": 11,
    "amount": "5000.0",
    "discount_rate": "0.5",
    "platform_fee": "200.0",
    "conversion_fee": "300.0",
    "vat": "300.0",
    "amount_to_pay": "3300.0",
    "id": 4,
    "maker_id": 3,
    "created_at": "2019-07-24T02:02:16.486Z",
    "updated_at": "2019-07-28T14:41:47.736Z",
    "paid_amount": "0.0",
    "base_amount": "2500.0",
    "taxable_amount": "3000.0",
    "address": null
}
```

**Comment by ggomaeng** [comment]
Case closed Mr. 김두둥
