### ISSUE TITLE
Forgot Password?

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#107]
We need to add a `Forgot password?` text button on the login section.
1. Forgot password?
2. 
*Reset password*
Enter the email address associated with your account, and we’ll email you a link to reset your password.
--- Email input field ---
3. A link to reset your password has been sent to xxx@yyy.com.

![Screenshot 2019-07-28 05 52 39](https://user-images.githubusercontent.com/15100667/62002444-1b6ebc80-b0fc-11e9-93a4-2ddf72787b8f.png)

**Comment by cyh76507707** [comment]
Email content

```
Hi [username],

We’ve received a request to reset your password.
If you didn’t make the request, just ignore this message. Otherwise, you can reset your password using this link:

--- Click here to reset your password ---

Thanks,
HUNT Team
```

**Comment by sydneyitguy** [comment]
@ggomaeng 
Success output: `SENT`

Possible error outputs:
```
ALREADY_CONFIRMED
EMAIL_DOES_NOT_EXISTS
EMAIL_FAILED
```

**Comment by sydneyitguy** [comment]
@ggomaeng API is done and deployed on Staging (doc is on Postman)

**Comment by cyh76507707** [comment]
@sydneyitguy @ggomaeng 
We still need a "forgot password" feature on the log in page.

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/62449397-0ac9e080-b7a5-11e9-86df-73ea7dcc6a86.png)
