### ISSUE TITLE
Show preview page after the campaign submission

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#108]
After a Maker submit the campaign, we may need to keep show the summary page or the preview page of his/her campaign.

![Screenshot 2019-07-28 06 02 21](https://user-images.githubusercontent.com/15100667/62002499-6937f480-b0fd-11e9-9ba8-a813c5ae038e.png)

**Comment by ggomaeng** [comment]
Implemented in 70183803
![image](https://user-images.githubusercontent.com/18402191/62006999-21f44700-b183-11e9-815b-38457496c127.png)
