### ISSUE TITLE
Quest navigation on a Hunter's quest dashboard

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#110]
When a Hunter click the navigation icon to see the prev quest on the Quest Dashboard view, he/she is not able to get back to the current stage unless refresh the page.

![ bug-4](https://user-images.githubusercontent.com/15100667/62002592-1eb77780-b0ff-11e9-8380-4d7f1846079b.gif)

**Comment by ggomaeng** [comment]
Fixed in 90559b89
