### ISSUE TITLE
Internal wallet transaction text

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#117]
![image](https://user-images.githubusercontent.com/1332279/62003052-83002880-b14b-11e9-9e19-260ce695cbf9.png)

`ETH Wallet (undefined)`=> Please use `sender_email || sender_steem_username` field there

If `sender_email == admin@hunt.town`, Show "Reviewhunt" instead

**Comment by ggomaeng** [comment]
Should be fixed in 5e99283. Couldn't test `If sender_email == admin@hunt.town, Show "Reviewhunt" instead`, but it should work.
