### ISSUE TITLE
Default dashboard menu for maker

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#119]
![image](https://user-images.githubusercontent.com/1332279/62003650-243fac80-b155-11e9-8e00-f34b8e19e723.png)

As a maker, when I go to "dashboard", it automatically shows `Create Campaign` menu opened by default even if I have a running campaign.

I think the condition to open create campaign menu by default only if "when maker has no campaigns on the list"

**Comment by ggomaeng** [comment]
Now, it fetches the first item in the campaigns list if the length is greater than 0. Else, it shows the create campaign tab
