### ISSUE TITLE
Request edit status

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#122]
![image](https://user-images.githubusercontent.com/1332279/62009048-7d2f3500-b195-11e9-8034-a630994d0632.png)

1. It should show left menu submenu like `draft` status
2. It should show `review_comment` message so makers can see what's wrong

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/62030545-43574080-b220-11e9-9a0f-0bba41d4fcfb.png)
