### ISSUE TITLE
Rejected status

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#123]
![image](https://user-images.githubusercontent.com/1332279/62009061-caaba200-b195-11e9-8807-79ea1851912a.png)

It should show `review_comment` so makers can see what's wrong

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/62027735-6d593480-b219-11e9-9569-46c6b0aac709.png)
