### ISSUE TITLE
Maker - Beta Period

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#128]
Show this message below when a signed-up Maker tries to create a campaign.
(Zeplin: `Maker - Beta`)

![Screenshot 2019-07-28 16 22 25](https://user-images.githubusercontent.com/15100667/62009386-7af9b600-b156-11e9-8d77-87ba3af8f03d.png)

And link this Google form when the person click the `Ask Team` button.
https://docs.google.com/forms/d/e/1FAIpQLSeMN8t1o3nyQ_59T-gMczgZWD5K3r25hJXdGo8qaRXL9qvJ7w/viewform?usp=sf_link

**Comment by ggomaeng** [comment]
Set DEBUG_BETA true in MakerProfile for now.

**Comment by sydneyitguy** [comment]
closed in favor of open beta
