### ISSUE TITLE
Maker Dashboard Default Screen

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#129]
I think we need to set the default page for the Maker. Please create a summary list page of all the campaigns that the Maker has run so far.

Zepline: `Maker - Dashboard Default`
![Screenshot 2019-07-28 16 29 59](https://user-images.githubusercontent.com/15100667/62009423-f9eeee80-b156-11e9-9309-1235f0476737.png)

This is an empty state when there's no campaign has run.
Zepline: `Maker - No Campaigns`

![Screenshot 2019-07-28 16 30 07](https://user-images.githubusercontent.com/15100667/62009430-08d5a100-b157-11e9-9e10-f0b7fa36437d.png)

**Comment by ggomaeng** [comment]
Then do we really need the Collapsible menu on the left side? I feel like it's redundant.

![image](https://user-images.githubusercontent.com/18402191/62009821-2d08a080-b19e-11e9-8063-3169a5d95223.png)

**Comment by cyh76507707** [comment]
Yeah I think it's still more convenient to have the sidebar when there're multiple campaigns. Maybe only the draft / ongoing campaigns can be visible on the collaps menu.

**Comment by sydneyitguy** [comment]
@cyh76507707 

Let's just remove the side bar menu and make it consistent with the hunter Quest dashboard flow.

Makers may have only 2-3 campaigns maximum anyway & most likely one campaign running at a time.
