### ISSUE TITLE
List view of the quest dashboard - data is not updated

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#134]
<img width="483" alt="Screenshot 2019-07-28 20 40 06" src="https://user-images.githubusercontent.com/15100667/62011987-14858f80-b178-11e9-8aaf-324e78c170f9.png">

Seems the following data is not updated:
1. The bar graph
2. Earned, Grab more tag
3. $ amount --> HUNT amount

Check the design of `H-Dashboard` on Zeplin

**Comment by cyh76507707** [comment]
Also please change `Grab more` to be `Next get`
(ex_ Next get 835 HUNT)

**Comment by ggomaeng** [comment]
Duplicate of #146
