### ISSUE TITLE
Cat empty state is appeared when a Maker logged in

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#137]
I logged in via a Maker, and the cat is appeared when there are running campaigns.

<img width="1323" alt="Screenshot 2019-07-28 21 04 44" src="https://user-images.githubusercontent.com/15100667/62012225-64b22100-b17b-11e9-91e2-ffb86127666e.png">

**Comment by sydneyitguy** [comment]
@cyh76507707 
@ggomaeng really liked that design, so we wanted to put it no somewhere.
I think we can just leave the graphic for makers to see (when user logged in as a maker).
That way we can lead makers to "create a campaign" over browsing them
