### ISSUE TITLE
Changes in the main page

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#141]
1. About --> I'm a Maker
2. Headline --> EARN REWARDS FOR TRIAL & BUZZ
3. Remove the "Learn more" button
<img width="1431" alt="Screenshot 2019-07-29 14 12 16" src="https://user-images.githubusercontent.com/15100667/62051267-eac97880-b20a-11e9-9bcf-3c7a7b9d02cc.png">

3. Hunters on quest --> Hunters Joined
(if the number is less than or equal to 1, it should be `1 Hunter Joined`)
<img width="147" alt="Screenshot 2019-07-29 13 08 32" src="https://user-images.githubusercontent.com/15100667/62051299-ffa60c00-b20a-11e9-96a5-147de49a1ea4.png">

4. Join Now button --> Learn More button
<img width="1432" alt="Screenshot 2019-07-29 13 07 55" src="https://user-images.githubusercontent.com/15100667/62051341-10ef1880-b20b-11e9-8515-37bd4f93531c.png">

**Comment by sydneyitguy** [comment]
"EARN REWARDS FOR TRIAL & BUZZ" -> Is it really easy to understand by noobs?
If I never knew about Reviewhunt, I would think..
"Trial of what?.. and what is buzz?"

How about "TRY NEW PRODUCTS EVERYDAY AND EARN REWARDS" ?

If we want to focus on "Buzz" part,
"SPREAD COOL PRODUCTS AND EARN REWARDS"

I don't think we can put 2 together into one short sentence.

What do you think @ggomaeng

**Comment by cyh76507707** [comment]
Let's choose between

1.
SPREAD COOL PRODUCTS
EARN REWARDS

2.
CREATE PRODUCT BUZZ
EARN REWARDS

3.
TRY OUT COOL PRODUCTS
EARN REWARDS

I like 2 or 3.

**Comment by ggomaeng** [comment]
How about:

TRY COOL PRODUCTS
GET PAID

**Comment by sydneyitguy** [comment]
TRY COOL PRODUCTS
EARN REWARDS

**Comment by ggomaeng** [comment]
Changes reflected.
