### ISSUE TITLE
Add app links on quest dashboard

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#143]
![image](https://user-images.githubusercontent.com/1332279/62061275-ca78d880-b261-11e9-87d9-b2430573774e.png)

Normally hunters may start the quest from the quest dashboard,
and will download the app after they join quest 1.

But now I have to go back to "campaign brief" to get the download link.
I guess we can add these download buttons on the campaign dashboard too

![image](https://user-images.githubusercontent.com/1332279/62061367-ff852b00-b261-11e9-8747-bb6b24090daa.png)

**Comment by cyh76507707** [comment]
@ggomaeng Let's change the "brief" button to be square type again, and put the link button there as below:

![Screenshot 2019-07-29 17 38 38](https://user-images.githubusercontent.com/15100667/62065821-b6b08080-b227-11e9-861b-ad78ad3c1f08.png)
