### ISSUE TITLE
Conversion rate is incorrect

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#147]
https://github.com/Steemhunt/reviewhunt-web/issues/65
This issue seems not fixed

![image](https://user-images.githubusercontent.com/1332279/62069843-26e4f380-b274-11e9-816a-161a2dbcef65.png)

HUNT should be fixed and USD value should be changed

**Comment by ggomaeng** [comment]
Now it's really fixed :p
