### ISSUE TITLE
Wrong reward amount on the notification messages

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#150]
"Your submission was confirmed. You will earn 0.5 HUNT after this campaign is all finished"
`0.5 HUNT` seems not the right reward amount.

![Screenshot 2019-07-29 21 29 15](https://user-images.githubusercontent.com/15100667/62080181-09019980-b248-11e9-8e50-3d59bf430175.png)

**Comment by cyh76507707** [comment]
@sydneyitguy It seems the USD value is now appear on the notification message with the HUNT unit.
![image](https://user-images.githubusercontent.com/15100667/62377101-0f3e9100-b53a-11e9-9527-b77ac1ba2914.png)

**Comment by ggomaeng** [comment]
It seems that the conversion was only applied to Quests, not on reviews and buzz channels. It should be fixed in afa666bb
