### ISSUE TITLE
Scroll position issue

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#154]
When to move to another page, sometimes there're scroll position issue. I'm not sure if this is a constant issue cause sometimes it's not happened.

![bug-6](https://user-images.githubusercontent.com/15100667/62147905-779a3200-b2f0-11e9-9f7d-f53fe93f09c0.gif)

**Comment by ggomaeng** [comment]
Should be fixed in the latest push
