### ISSUE TITLE
System Error: FORBIDDEN_STATUS

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#161]
Can't move to the next step from the budgeting because of `System Error: FORBIDDEN_STATUS`
<img width="1586" alt="Screenshot 2019-07-30 18 46 12" src="https://user-images.githubusercontent.com/15100667/62152653-dcf32080-b2fa-11e9-8822-a65513679ef6.png">

**Comment by cyh76507707** [comment]
Also, this seems related to that issue... but

When I created another Maker account, and clicked the dashboard, and the another Maker's draft was appeared like this:

<img width="1634" alt="Screenshot 2019-07-30 19 00 35" src="https://user-images.githubusercontent.com/15100667/62153436-6fe08a80-b2fc-11e9-80cf-c13ce65a9a68.png">

**Comment by ggomaeng** [comment]
System Error: FORBIDDEN_STATUS seems to be an API issue. The second issue was caused due to not resetting the state. Second issue should be fixed in 7ab69be2
