### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#163]
1. Name
Reviewhunt - Try Cool Products, Get Rewards

2. Description
Try out cool new tech products such as a mobile apps, games, web apps, and gadgets before they have gained mainstream attention and you'll also earn rewards.

**Please replace any words related to Steemhunt.**
![Screenshot 2019-07-31 02 10 39](https://user-images.githubusercontent.com/15100667/62176200-7987e380-b338-11e9-98a4-72a7d6e4fab2.png)

**Comment by ggomaeng** [comment]
should I keep 
```
<meta name="twitter:site" content="@steemhunt" />
<meta name="twitter:creator" content="@steemhunt" />
``` the same?

**Comment by sydneyitguy** [comment]
@ggomaeng You can leave those twitter handles for now
