### ISSUE TITLE
Permission denied issue from Makers account

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#171]
I don't know what causes this error message, but all the Makers' account so far are having the same error message when they go on the Dashboard page.
![Screenshot 2019-07-31 13 03 02](https://user-images.githubusercontent.com/15100667/62210365-e2507980-b393-11e9-9cf9-1d3aff6ee1bd.png)

**Comment by sydneyitguy** [comment]
fixed https://github.com/Steemhunt/reviewhunt-api/commit/117f07187db10dbefe5deaf5e9bbe88e1e1f86f8
