### ISSUE TITLE
Moderation - full screen mod

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#172]
Please make the full screen mod really "full" screen. Or, let's make the image can be on full-screen mode like the campaign brief page (I guess this will be more effective to check).

![Screenshot 2019-07-31 13 14 16](https://user-images.githubusercontent.com/15100667/62210922-3445cf00-b395-11e9-8fde-92f4e28de837.png)

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/64506658-570fbf80-d313-11e9-98d0-5e0b3050dd37.png)
