### ISSUE TITLE
[BUG-REPORT] Not Updated Submission

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#175]
![image](https://user-images.githubusercontent.com/36227271/62244383-e6bb7780-b411-11e9-8e47-34e0af76ce11.png)

I havent submitted a quest for Q2 yet, but it shows my recent submission at Q1, this also applies to every quest on the dashboard. But to fix this issue temporarily, the hunter must click Q1 button and the reclick the Q2 button.

**Comment by sydneyitguy** [comment]
Fixed with - https://github.com/Steemhunt/reviewhunt-web/commit/daf3c724c8945188bde4237de13bf56f252c7162
