### ISSUE TITLE
Progress bars are not matching

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#176]
![Screenshot 2019-07-31 21 22 08](https://user-images.githubusercontent.com/15100667/62245311-434e7080-b3d9-11e9-962b-fda6c177ff02.png)
![Screenshot 2019-07-31 21 21 47](https://user-images.githubusercontent.com/15100667/62245312-434e7080-b3d9-11e9-92e5-088a329eff15.png)

The remaining budget on the campaign brief and dashboard are not matching.

**Comment by sydneyitguy** [comment]
put discussion on Discord#dev

**Comment by sydneyitguy** [comment]
@ggomaeng 
Ok so let's change the maker dashboard balance to percentage
