### ISSUE TITLE
Add text field on Quest design

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#188]
Let's add a checkbox between proof example and guidelines with saying, `Add a text proof` so that Makers can accept some link or text-based proof together. 

For example, they can add link of the post together when they need to post some content proof. It will make easier to moderate the submission.

![Screenshot 2019-08-01 11 43 58](https://user-images.githubusercontent.com/15100667/62287490-de832c80-b451-11e9-8521-c74bed32e6b2.png)

**Comment by sydneyitguy** [comment]
@cyh76507707 
How about just add `proof url` for general quests too instead of creating a new field `proof text`?

**Comment by cyh76507707** [comment]
1. Below the proof example section, add a checkbox with saying `Require to provide the URL of the quest proof.`
2. Once the maker clicked the button, it should have an URL input field on the quest submission page as similar with the buzz submission page.
<img width="662" alt="Screenshot 2019-08-08 13 16 50" src="https://user-images.githubusercontent.com/15100667/62734158-386e8e00-ba20-11e9-9559-7483e2c25e5d.png">

**This feature is required for the Mosaeek's 2nd campaign.**
