### ISSUE TITLE
[BUG-REPORT] Not Updated

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#198]
![image](https://user-images.githubusercontent.com/36227271/62379423-85161d00-b579-11e9-822a-d2b3ecfa8817.png)

I noticed that my current subscribers and instagram followers are not in match with the profile. The refresh button wouldn't do, in that case I manually removed it and input my channel again.

**Comment by sydneyitguy** [comment]
I just tried refreshing, and it seems it's refreshed with correct data.
Did you get any error message here?

**Comment by Chuuuckie** [comment]
![image](https://user-images.githubusercontent.com/36227271/62446614-b79c6180-b795-11e9-8bb0-2c58898e31ae.png)

It is still wrong though, this is the error message behind it.
