### ISSUE TITLE
Referral

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#199]
1. Add referred user input after the sign up process
2. Bounty bonus for referrers

**Comment by cyh76507707** [comment]
Zeplin - `referral`

![referral](https://user-images.githubusercontent.com/15100667/62448508-ec8dc180-b75f-11e9-8d8f-4555dc74cede.jpg)

**Comment by sydneyitguy** [comment]
Final decision:
1. 피추천인 (Hunter)이 올린 버즈 컨텐츠의 5% 보상을 추천인이 보너스로 받음
2. 피추천인 (Maker)가 진행하는 캠페인의 버짓의 5%를 추천인이 보너스로 받음
3. 피추천인은 별도의 보너스나 이득 없음
4. 초대코드 입력 하는 인터페이스 없음, 초대 링크로만 hidden tracking

**Comment by sydneyitguy** [comment]
Invitation URL format will be:
https://review.hunt.town/r/123456

**Comment by sydneyitguy** [comment]
a87989f

**Comment by ggomaeng** [comment]
Invitation url format has changed to:
https://review.hunt.town/**i**/123456

**Comment by cyh76507707** [comment]
Please add the referral info together on the `rh-quest-log` on our Discord group. The msg can be below this log
> Submitted] #183. ch***@***.com (username) - Reserved: $0.5 - link

The msg can be like this:
`Referrer: UserName (i/4) - Reserved: 54.35 HUNT - Total: 102.55 HUNT`

**Comment by sydneyitguy** [comment]
This is not related to this ticket.
I just created a new ticket for this - https://github.com/Steemhunt/reviewhunt-web/issues/246
