### ISSUE TITLE
Viral page

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#200]
Social Bigmac Index

- [x] Weird responsiveness around 1300px width
- [x] Show dates on "Just earned" section and remove slide up effects with just 10 recent results
- [x] "Just earned" section font size from 1.375rem -> 1.1rem
- [x] og:url metatag is wrong, so it fetches the main page (canonical url shouldn't be set)
- [x] Attributes to hide:
- [x] og:image resizing @cyh76507707
- [x] Cat image shadow issue
- [x] Twitch URL parsing
- [x] Translation file
- [x] Cache key should be case insensitive
- [x] Youtube channel_id, username - redesign
- [x] Pro****7 just earned $105.3 ~~ --> This sentence is broken in a mobile view.
- [x] When there are so many burgers -> when a user scroll down to below, the burgers fall down (drain out) with couple of secs latency time.
- [x] On a mobile view, please make left/right margins except for the black result box.
- [x] ENG / KOR button at footer area.
- [x] Add a button on the nav bar on RH --> Big Mac Index

**Comment by cyh76507707** [comment]
Zeplin Design
- `v-main`
- `v-analysing`
- `v-result`
- `v-burgers`

og-images:
https://www.dropbox.com/sh/5bdyhoqojmero1o/AADf1VQBXL9J3HBwW9mQ99-Ka?dl=0

og-image `default`
- Title: How much is your one piece of content worth?
- Sub: Check out how many Bic Macs you can buy with your social media content.

og-image `share the result`
- Title: [account name]'s social content is worth [$price]!
- Sub: Click here to see how many Bic Macs your social media is worth.

`v-burgers`
--> Please change the burger size when the number of burgers are changed.
--> If less than 1, show the grumpy cat image.

**Comment by sydneyitguy** [comment]
Bic Mac Price in USA 2019: $5.58
https://www.statista.com/statistics/274326/big-mac-index-global-prices-for-a-big-mac/

**Comment by cyh76507707** [comment]
https://www.quandl.com/data/ECONOMIST-The-Economist-Big-Mac-Index
They have json data for Bic Mac index.

**Comment by sydneyitguy** [comment]
Let's just use a fixed value $5.58 instead of a API call everytime (I think this data only updates like once a year anyway)

**Comment by cyh76507707** [comment]
1. 랭킹 부분에 리뷰헌트쪽 채널 추가 데이터 연동 (처음 들어갔을때 참여한 사람들 숫자가 제법 있어야 하니까)
2. 리뷰헌트 "just earned" 데이터 (지금은 걍 목업임)
3. 한글화 작업 --> yml 파일 하나 만들어줘
4. 소셜 공유 버튼 --> 지금은 작동 안함
5. 다른 채널 분석해 보기 버튼 추가 --> 결과 검색한 다음에 다른거 검색해 보려면 새로고침 해야함
6. 반응형 디자인 (모바일에서 최적화 안된듯)
7. 이건 필수는 아닌데 여력이 있으면.. 햄버거 떨어질때 뭔가 효과음 있으면 좋을듯

**Comment by sydneyitguy** [comment]
It would be more convenient if user input a URL, front-end detects the domain name and change the channel selector accordingly

**Comment by sydneyitguy** [comment]
Can we also move the loading animation "after" the data fetch?

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/63151147-c9a6bb80-c043-11e9-8093-75092e3db2ce.png)

Text are not readable when there're full of burgers on the background.
I guess we can fix this issue by 2 potential ways:
1. add one more layer with opacity like 20% between the burger and the text layers
2. make burgers smaller and limit the max amount at about half screen filled (so users can still see if they scroll the content a bit upper side)

**Comment by cyh76507707** [comment]
Please change the og-images of the viral page as below:
files: `dropbox > viral site`

og-image `default`
* Title: How much is your one piece of content worth?
* Sub: Check out how many Bic Macs you can buy with your social media content.

og-image `share the result`
* Title: [account name]'s social content is worth [$price]!
* Sub: Click here to see how many Bic Macs your social media is worth.

**Comment by sydneyitguy** [comment]
TODO:
- [ ] Weird responsiveness around 1300px width
- [ ] Show dates on "Just earned" section and remove slide up effects with just 10 recent results
- [ ] "Just earned" section font size from 1.375rem -> 1.1rem

**Comment by sydneyitguy** [comment]
Renamed `buzz_channel_display_name` -> `buzz_channel_masked_name`

**Comment by sydneyitguy** [comment]
TODO:
- [ ] og:url metatag is wrong, so it fetches incorrectly

![image](https://user-images.githubusercontent.com/1332279/63258013-0f6aba80-c2b6-11e9-8c3b-2441bd4d6233.png)

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/63267772-b4dd5880-c2cd-11e9-9458-4ff16fc08764.png)
truncate the title

**Comment by cyh76507707** [comment]
@ggomaeng 
Profile image from Twitter is broken.
![Screenshot 2019-08-19 14 10 42](https://user-images.githubusercontent.com/15100667/63268040-35c73080-c28b-11e9-9102-992d775487fa.png)

**Comment by sydneyitguy** [comment]
Mobile - download image button doesn't work
=> We may need to hide the button on mobile if that doesn't work

**Comment by sydneyitguy** [comment]
Let's change URL input interface to username.
We made it URL because Reviewhunt accepted `other` channels, but this viral page doesn't accept other channels, so username input is more intuitive.
(Also easier for removing duplications on ranking board)

I'll change the API accordingly.

**Comment by cyh76507707** [comment]
Some profile img from Steemit account is missing
https://review.hunt.town/bigmac?channel=steem&url=https%3A%2F%2Fsteemit.com%2F%40steemitblog

![Screenshot 2019-08-19 20 29 08](https://user-images.githubusercontent.com/15100667/63293429-0252c900-c2c0-11e9-836f-94cc7c7ffbed.png)

**Comment by sydneyitguy** [comment]
Instagram:
 - https://www.instagram.com/{id}
Youtube:
 - https://www.youtube.com/channel/{id}
 - https://www.youtube.com/user/{id}
Twitter
 - https://www.twitter.com/{id}
Medium
 - https://medium.com/@{id}
Steem
 - https://steemit.com/@{id}
Twitch
 - https://www.twitch.tv/{id}

Regular expression would be generally like:
```
/(https?:\/\/)?(www\.)?instagram\.com\/(?<id>[A-Za-z0-9_\-\.]+)/
```

For Youtube, if the URL matches with channel_id, send `is_channel_id` params `true`

API params:
- channel_type (string, lowercase)
- username (string)
- is_channel_id (boolean)

**Comment by cyh76507707** [comment]
Change title to be `Social Media Big Mac Index` / Please check all the SEO title too.

**Comment by sydneyitguy** [comment]
@cyh76507707 that user doen'st have profile image. We need a  default image for those cases.

**Comment by sydneyitguy** [comment]
Attributes to hide:
- Instagram: `view`
- Twitter: `comment`, `view`
- Medium: `view`
- Steemit: `view`
- Twitch: `post_count`, `like`, `comment`

**Comment by cyh76507707** [comment]
@ggomaeng Few changes.
1. Please make more opacity on the background burgers on a mobile view.
2. Change the color or `Clear Burgers` to be `#ff3cac` and make `border-radius` to be zero.
![IMG_1446](https://user-images.githubusercontent.com/15100667/63332257-226da100-c32f-11e9-8597-cafaeed761dc.PNG)

3. Make the vertical margin the same with horizontal margin.
![Screenshot 2019-08-20 09 46 14](https://user-images.githubusercontent.com/15100667/63332365-606ac500-c32f-11e9-830c-63a0ee8ed4ab.png)

**Comment by sydneyitguy** [comment]
- [ ] og:image resizing @cyh76507707 
- [ ] Cat image shadow cutting issue

**Comment by cyh76507707** [comment]
Mobile view (pixel 3a)
![69316104_2345869355675409_1737476432017227776_n](https://user-images.githubusercontent.com/15100667/63426101-f5da8780-c409-11e9-9f1e-797932848201.png)

**Comment by cyh76507707** [comment]
Some Youtube channels that has the hash-style username have errors to process.
![Screenshot 2019-08-21 14 26 02](https://user-images.githubusercontent.com/15100667/63435941-b454d700-c41f-11e9-9b19-bb61e8346800.png)

**Comment by cyh76507707** [comment]
Twitch also doesn't work.
![Screenshot 2019-08-21 14 29 37](https://user-images.githubusercontent.com/15100667/63436162-1e6d7c00-c420-11e9-99db-597c1502675b.png)

**Comment by ggomaeng** [comment]
@cyh76507707 
Mobile View should be fixed in the latest patch. For Twitch, you have to enter the username instead of the url. It should parse the username automatically in the latest patch, but let me add an extra validation saying that they should only enter the username.

**Comment by cyh76507707** [comment]
1. Pro****7 just earned $105.3 ~~ --> This sentence is broken in a mobile view.
2. When there are so many burgers -> when a user scroll down to below, the burgers fall down (drain out) with couple of secs latency time.
3. On a mobile view, please make left/right margins except for the black result box.

**Comment by cyh76507707** [comment]
Add a button on the nav bar on RH --> `Big Mac Index`
![Screenshot 2019-08-22 06 16 06](https://user-images.githubusercontent.com/15100667/63487757-5e764280-c4a4-11e9-98ea-f4f40271e711.png)
