### ISSUE TITLE
Change the Green color on wallet

### ISSUE THREAD

**Issue by jayplayco** [Steemhunt/reviewhunt-web#201]
![image](https://user-images.githubusercontent.com/2923960/62431788-a89dbb00-b765-11e9-80b3-59030a0bc44f.png)

* Dashboard> Wallet > Transfer
The Popup shows the Available Balance of Hunt, etc. but the choosed Green color for the 
1. Amount of Hunt Token
2. MAX
3. Check Bar
4. Submit button 

Are in a NEON Green that are hardly readable on a white background. It would need to be changed in a more darker color or either the background would need to be matched to a more readable color.

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/63015574-46af2500-becc-11e9-8919-9c6161b8e84e.png)
@cyh76507707 Please give us guideline for this popup

**Comment by ggomaeng** [comment]
Currently, our primary color is #50fdc6, which is automatically applied to sub components like checkboxes, and buttons. How about we change the primary color to #3fcaff?

![image](https://user-images.githubusercontent.com/18402191/64589565-5a24b180-d3e0-11e9-816a-c8b3d211994b.png)

**Comment by sydneyitguy** [comment]
let's just make the button to the simple flat black one like below:
![image](https://user-images.githubusercontent.com/1332279/64607915-6fabd280-d404-11e9-9247-4d297a45908e.png)
