### ISSUE TITLE
Change buzz channels by admin

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#206]
Please add a feature that allows admin to change the channel type for other channel submission like this:

![Screenshot 2019-08-05 19 47 18](https://user-images.githubusercontent.com/15100667/62487596-2a1f3880-b7ba-11e9-8a63-be2096839847.png)

**Comment by ggomaeng** [comment]
@sydneyitguy is this possible to implement on the client side with the current API?

**Comment by ggomaeng** [comment]
This was due to estimated price being 0. Should be fixed.
