### ISSUE TITLE
[BUG-REPORT] Facebook Error

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#207]
![image](https://user-images.githubusercontent.com/36227271/62493886-c3733c80-b804-11e9-9391-fff6765966d5.png)

Followers for Facebook not fetched, 

current: 2k friends 308 followers for profile page
current: 2k+ likes and followers from a business page

**Comment by sydneyitguy** [comment]
We cannot fetch channel statistics from "Other" channels.
We will manually update the numbers once any content gets reviewed
