### ISSUE TITLE
Tick box too thick?

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#21]
On the design:
![image](https://user-images.githubusercontent.com/1332279/61776422-f0534700-ae35-11e9-9fe5-804caab0dea1.png)

but it is now:
![image](https://user-images.githubusercontent.com/1332279/61776390-e3ceee80-ae35-11e9-80a8-8ee7c638ea8d.png)

Probably because it use SVG icon instead of round border.
If we don't want to add a thin SVG icon only for that, I guess we can just use Ant Design's default checkbox option.

![image](https://user-images.githubusercontent.com/1332279/61776546-3b6d5a00-ae36-11e9-85a8-f173dad05bc2.png)

What do you think? @cyh76507707

**Comment by ggomaeng** [comment]
It was due to using provided icons from antd design. I changed the  icon from check-circle to check with custom border css.

![image](https://user-images.githubusercontent.com/18402191/61806700-2367fb80-ae73-11e9-97af-3a056ef3eaa0.png)
