### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#211]
Page titles and meta tags have to be different representing each page's content.
We can use [React Helmet](https://github.com/nfl/react-helmet) for that.

Pages to cover:

- [x] Main page
- [x] Campaign
- [x] Profile / Dashboard
- [x] Signup / Login

Items to take care:

- [ ] Page title
- [ ] Meta description, og:description (160 characters)
- [ ] og:url
- [ ] og:image

Example
```jsx
<Helmet>
  <title>{titleize(post.title)} - {post.tagline} | Steemhunt</title>
  <meta name="description" content={truncate(post.description, 160)}>
  <meta property="og:description" content={truncate(post.description, 160)} />
  <meta property="og:image" content={getCachedImageHack(post.images[0]['link'], 1200, 630, true)} />
  <meta property="og:url" content={`${process.env.PUBLIC_URL}/@${post.author}/${post.permlink}`} />
</Helmet>
```

**Comment by ggomaeng** [comment]
@cyh76507707 Can you provide necessary information for the meta tags?

**Comment by cyh76507707** [comment]
name = Reviewhunt | Try Cool Products, Earn Rewards
description = Reviewhunt is a marketing hub to build comprehensive early-users through serial quest missions.
og:images --> check dropbox
please change the favicon too.

**Comment by sydneyitguy** [comment]
@cyh76507707 Let's use `-` or `: ` instead of `|`

**Comment by ggomaeng** [comment]
I'm really not sure what to add for Profile / Dashboard view, because there really is no public profile url for other people to visit. @sydneyitguy

**Comment by sydneyitguy** [comment]
@ggomaeng If it's not a public URL, we can just leave the default metatags

**Comment by ggomaeng** [comment]
Created MetaHelmet component with the following default props:
```
title: "Reviewhunt - Review Cool Products, Earn Rewards",
description: "Try out cool new tech products such as mobile apps, games, web apps, and gadgets and earn rewards.",
image: `${process.env.REACT_APP_PUBLIC_URL}/og-image-1200.png`,
image1024: `${process.env.REACT_APP_PUBLIC_URL}/og-image-1024.png`,
url: process.env.REACT_APP_PUBLIC_URL
```

Home:
```
<MetaHelmet
        description="Reviewhunt is a marketing hub to build comprehensive early-users through serial quest missions."
        image={`${process.env.PUBLIC_URL}/home-image-1200.png`}
        image1024={`${process.env.PUBLIC_URL}/home-image-1024.png`}
      />
```

Campaign:
```
<MetaHelmet
            title={_.capitalize(currentCampaign.product_name)}
            description={_.truncate(currentCampaign.description, {
              length: 160
            })}
            image={currentCampaign.images[0]}
            image1024={currentCampaign.images[0]}
            url={`${process.env.PUBLIC_URL}/campaigns/${currentCampaign.id}`}
          />
```

Profile:
```
<MetaHelmet title={"Profile - Reviewhunt"} />
```

About:
```
<MetaHelmet title={"About - Reviewhunt"} />
```

Signup / Login
```
<MetaHelmet title={"Signup - Reviewhunt"} />
...
<MetaHelmet title={"Login - Reviewhunt"} />
```

**Comment by ggomaeng** [comment]
Please check the content and close the issue if everything seems right @sydneyitguy @cyh76507707
