### ISSUE TITLE
Maker - beta

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#212]
Zeplin - `Maker - beta`
- Open the simple form as below.
- After the submission, please show the notification msg.
- Button before submission: `SUBMIT`
- Button after the submission: `EDIT`

![Maker - Beta](https://user-images.githubusercontent.com/15100667/62599935-761acc00-b8e5-11e9-895b-bc4e620a840e.jpg)

**Comment by sydneyitguy** [comment]
Will open open-beta interface with Crisp for this
