### ISSUE TITLE
Create campaign button - Maker's main

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#215]
Please add `Create Campaign` button on the main page ONLY for Makers.

<img width="1507" alt="Screenshot 2019-08-07 13 05 02" src="https://user-images.githubusercontent.com/15100667/62621587-2b647880-b914-11e9-955f-07b398a2afdb.png">

**Comment by sydneyitguy** [comment]
I added a button that links to 
`/profile?campaignId&tabIndex=create_campaign`

but when there's other campaigns on the list, it automatically redirects to edit page like
`/profile?campaignId=9&tabIndex=campaigns`

I will leave this fix to @ggomaeng
