### ISSUE TITLE
[SUGGESTION] Add a Total Bounty Accumulated

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#216]
![image](https://user-images.githubusercontent.com/36227271/62646235-6c927200-b980-11e9-8a79-bb0c4c52e999.png)

There should be a feature where hunters would know how much they are already earning from doing quests. eg - Total Bounty Earned so Far

**Comment by sydneyitguy** [comment]
I guess we can calculate this from the client side?

**Comment by sydneyitguy** [comment]
API returns `earned` attributes on `/campaigns/mine.json` - so you can add up those values
