### ISSUE TITLE
[BUG-REPORT] Access to Future Campaigns?

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#218]
If these links are for future campaigns, I think its good to keep this as a secret or hide it for a meanwhile.

https://review.hunt.town/campaigns/7 -- POP ART

https://review.hunt.town/campaigns/8 -- MARQ

**Comment by sydneyitguy** [comment]
Valid point! 👍🏻

@ggomaeng I guess we should hide `draft` data. I will just render 404 on API side if the campaign is before "running" status.

However, do we use that `/campaigns/:id.json` API on creation interface too? What other places do we use that API except the detail page?

**Comment by ggomaeng** [comment]
It's called when the Maker is drafting/reviewing a campaign. For example, when they click on the campaign item in the profile page, the api is called. I think we can fix this from the server side by requiring a token when the status of the campaign is not running.
