### ISSUE TITLE
[BUG-REPORT] Ease of Access by deleting Elements

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#219]
![image](https://user-images.githubusercontent.com/36227271/62731423-b2b90580-ba54-11e9-84c2-20961f36f7eb.png)

If you want to close a campaign and it shouldnt be readable because it is coming soon, a campaign must not be released its information from its quests this easily I guess.

**Comment by Chuuuckie** [comment]
![image](https://user-images.githubusercontent.com/36227271/62731553-04619000-ba55-11e9-900d-e0b1e775cb86.png)

Addition...

**Comment by sydneyitguy** [comment]
Fixed by putting a black modal if campaign hasn't started

**Comment by Chuuuckie** [comment]
Ill be testing it again if there will be more campaigns soon.
