### ISSUE TITLE
Quest 4, 5 - Review, Buzz quests

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#22]
![image](https://user-images.githubusercontent.com/1332279/61777515-fc400880-ae37-11e9-8933-ff3197d4b9a8.png)

We need

1. Static image for both
2. Criteria text from the maker's input (form should be pre-filled with our text, and user can edit)

**Comment by cyh76507707** [comment]
Zeplin - `Campaign detail - 2`
![Screenshot 2019-07-26 06 35 43](https://user-images.githubusercontent.com/15100667/61928193-9c4c7d80-af6f-11e9-9a2b-8b8cbfd24584.png)

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/61940011-8a9ac280-afcf-11e9-9457-3938c7325ec4.png)

**Comment by ggomaeng** [comment]
I will add usd value next to the total bounty fund.
