### ISSUE TITLE
Campaign Creation Onboarding Messages

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#220]
Please add these two for the purpose of giving a guide for makers to create campaigns by them selves.

1. Step description on each step --> This should be located under each step header.
![Screenshot 2019-08-08 14 54 44](https://user-images.githubusercontent.com/15100667/62734326-a6b35080-ba20-11e9-8dd6-4b78eec330f8.png)
2. Tooltip icon --> next to some section title that requires to provide clearer guide

I wrote the header descriptions and tooltip content here - https://docs.google.com/document/d/1XGcUgyHYUs9Z7geBWwjHiZeGbYl6YZvNBju1iIVeilQ/edit?usp=sharing.

**This is necessary improvement when we launch the open beta to lower the bounce rate when makers try to submit campaigns bye themselves.

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/62874015-6d018300-bd5b-11e9-976d-c47afbd86deb.png)

"default suggestion" ?
