### ISSUE TITLE
Finished campaigns on hunter's dashboard

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#226]
Please make finished campaigns still available to see their result. 

![Screenshot 2019-08-12 14 38 21](https://user-images.githubusercontent.com/15100667/62869130-1b330b80-bd0f-11e9-9852-a353ddb44879.png)

**Comment by sydneyitguy** [comment]
Let's make the default filter as "All" and show finished campaigns with half opacity

**Comment by cyh76507707** [comment]
1. Make "All" as a default setting.
2. Put finished campaigns below, and give some opacity so that it looks like finished one.
