### ISSUE TITLE
Moderation on quest submissions

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#24]
Case

1. General and Review quests => "Approve" or "Reject"
2. Buzz quests => "Rate" or "Reject" (should change status "approved" if rate >= 1)
3. Buzz quests with "Others" channel => this is tricky, see below:
  3-1. Show input form and receive "reward estimation" via PUT /buzz_channels/:id.json
![image](https://user-images.githubusercontent.com/1332279/61780554-ba19c580-ae3d-11e9-9fc4-ff8053b091f4.png)
  3-2. "Rate" or "Reject" with the reward estimation

**Comment by ggomaeng** [comment]
Fixed in bc73f99d
