### ISSUE TITLE
Multiple re-renderings issue on maker dashboard

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#241]
https://review.hunt.town/profile?campaignId=5&tabIndex=campaigns

When there're many items on moderation interface grid, browser almost went down (CPU usage).
I guess it could be a multiple unnecessary re-rendering on that page.

**Comment by ggomaeng** [comment]
The image component in the submitted item is now lazy loaded; if this does not improve the performance I think we should implement a method where new items are added when the scroll reaches the bottom of the list.

**Comment by ggomaeng** [comment]
Multiple rerendering has been fixed, but I can't reproduce the freezing experience on my end.
