### ISSUE TITLE
[BUG-REPORT] Error Refreshing Buzz Channels

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#255]
![image](https://user-images.githubusercontent.com/36227271/63455934-602e0f00-c480-11e9-98ec-8bc6f36b1d33.png)

Parameter Missing...

**Comment by ggomaeng** [comment]
What kind of channels do you have added on the list, @Chuuuckie?

**Comment by sydneyitguy** [comment]
ba28616, 5d877fa, e606571
