### ISSUE TITLE
[SUGGESTION] Reserve Tokens for Users on QUEST

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#259]
There must be token reserved where a USER is already doing its quest in a Span of 3 days, or maybe an option if tokens are reserved and did not comply and submitted the task with in the span of 3 days. The user is impossible to appeal for that option reserved tokens.

**Comment by sydneyitguy** [comment]
I'm not sure if I understood your suggestion correctly.

We reserve token bounties from the bounty pool when a hunter "joined" the quest.
If the quest submission approved, we keep the reserve until the distribution.
Otherwise (when rejected), we put the reserve back to the bounty pool.
