### ISSUE TITLE
Empty campaigns on Maker's profile menu

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#26]
This looks like it's broken little bit when a maker first signed up and see their empty profile page.

![image](https://user-images.githubusercontent.com/1332279/61840391-fac02000-aecb-11e9-892f-e26f1ba2883c.png)

I guess we can just hide the `Campagns` section entirely and show `Create Campaign` section instead when `Campaigns` are empty

**Comment by ggomaeng** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/18402191/61842030-b0da3880-aed1-11e9-9213-713d13bafbc2.png)

I think another way we can handle this is to use <Result/> component from antd like below:
![image](https://user-images.githubusercontent.com/18402191/61842055-c8b1bc80-aed1-11e9-9211-e6aed64b5c22.png)
