### ISSUE TITLE
No running campaigns on the main page

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#27]
![image](https://user-images.githubusercontent.com/1332279/61840555-7f12a300-aecc-11e9-98b4-fc1b23a5148b.png)

Let's add some empty page like

```
There is no running campaigns at the moment.
218,837 hunters are waiting for reviewing your product! 
Sign Up as a Maker to start your campaign >
```

@cyh76507707 design & sentences are necessary.

**Comment by cyh76507707** [comment]
Zeplin - `No Campaign`

![No Campaign](https://user-images.githubusercontent.com/15100667/61994546-963fc500-b073-11e9-90cc-273cdb8b3a0c.jpg)

**Comment by ggomaeng** [comment]
I think it would be nice if this section always shows for makers. If they're logged in, the text would be rendered differently i.e) Join as maker -> Create a campaign

**Comment by ggomaeng** [comment]
Responsiveness for tablets / mobile

![image](https://user-images.githubusercontent.com/18402191/62007399-e8720a80-b187-11e9-8914-8862c0ddeaf9.png)
