### ISSUE TITLE
depositor_name is not saved

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#275]
on payment - KRW option

I input the depositor_name, but the value wasn't saved properly

**Comment by sydneyitguy** [comment]
https://github.com/Steemhunt/reviewhunt-api/commit/f0568931d0d28d98aa8dec21a084167117542634

**Comment by ggomaeng** [comment]
I get an error of `error: "PARAMETER_MISSING"` with the following body:

![image](https://user-images.githubusercontent.com/18402191/64588108-6149c080-d3dc-11e9-9d84-4984fa0560b3.png)

**Comment by sydneyitguy** [comment]
Fixed https://github.com/Steemhunt/reviewhunt-api/commit/55a9c30b28c861694a760dfd84014b20b419a0ae
