### ISSUE TITLE
General Quest 3 => Bonus Quest

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#28]
We have renamed "General Quest 3" to "Bonus Quest" so it became an optional quest,
because makers may want to request something more complicated with a higher bounty.

Bonus Quest expiry will be 3 days (same as buzz quests).

Please make necessary changes on the quest form.

**Comment by ggomaeng** [comment]
Does it still have the same quest_type field "general_3"?

**Comment by sydneyitguy** [comment]
> Does it still have the same quest_type field "general_3"?
yes

**Comment by ggomaeng** [comment]
TODO: Add NumberInput for reward amount.

**Comment by ggomaeng** [comment]
Budget Slider has been added for each quest. 

![image](https://user-images.githubusercontent.com/18402191/61850911-703de780-aef0-11e9-8c9f-fcb0decc6b46.png)

![image](https://user-images.githubusercontent.com/18402191/61850883-58fefa00-aef0-11e9-8230-0fab9cdd52c2.png)
