### ISSUE TITLE
Changes for the campaign creation page

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#287]
<img width="544" alt="Screenshot 2019-09-23 11 54 58" src="https://user-images.githubusercontent.com/15100667/65420412-feebb980-ddf8-11e9-8815-e3e4a96038f2.png">

- [x] - REVIEW --> APP STORE REVIEW
- [x] - App Store Review --> App Store (Apple)
- [x] - Play Store Review --> Play Store (Android)

<img width="630" alt="Screenshot 2019-09-23 11 58 05" src="https://user-images.githubusercontent.com/15100667/65420577-6a358b80-ddf9-11e9-9fae-7ee0bb23dd97.png">

- [x] - BUZZ --> BUZZ CONTENT

<img width="1229" alt="Screenshot 2019-09-23 11 59 13" src="https://user-images.githubusercontent.com/15100667/65420630-93561c00-ddf9-11e9-8234-dede82a25e96.png">

- [x] - Please add this title above the result boxes --> RESULT ESTIMATION
- [x] - Add a tool tip on the title above ((i) icon) --> The following numbers are a rough estimation based on our previous campaign results. The actual results may vary.
- [x] - EXPECTED HUNTERS --> HUNTERS TO JOIN
- [x] - ESTIMATED REVIEWS --> APP REVIEWS
- [x] - NUMBER OF BUZZ CONTENTS --> BUZZ CONTENT

<img width="403" alt="Screenshot 2019-09-23 12 07 14" src="https://user-images.githubusercontent.com/15100667/65421070-b2a17900-ddfa-11e9-8936-27783fdaf308.png">

- [x] - CONTINUE TO PAYMENT --> CONTINUE TO PROCEED
- [x] - Add a button to the left --> `ASK HELP` --> Open the chat box with a message

<img width="1183" alt="Screenshot 2019-09-23 12 08 45" src="https://user-images.githubusercontent.com/15100667/65421131-e7adcb80-ddfa-11e9-8d7b-f0fbf890e145.png">

- [x] - CHOOSE PAYMENT METHOD --> SET UP YOUR CAMPAIGN BUDGET
- [x] - Please choose the payment method you would like to use. --> Once you set your campaign budget, the team will contact you to finalise your campaign content and quest guidelines. The payment below is 100% refund guaranteed BEFORE you agree to begin your campaign with us.   

<img width="858" alt="Screenshot 2019-09-23 13 50 46" src="https://user-images.githubusercontent.com/15100667/65426934-2e0a2700-de09-11e9-9ed0-2867fa136fb1.png">

- [x] Your campaign was submitted --> Your campaign was requested
- [x] Please double check~~~  --> The team will contact you via the chat on the bottom right to finalise your campaign design within 24 hours. They will support you to create the design materials and quest guidelines for your campaign. 
- [x] Delete the thumbnail area (campaign img + summary)
- [x] MAKER INFORMATION --> REQUEST INFORMATION
- [x] Change the maker information area to be the summary of the campaign request as below:
```
Product Name: xxx
Product URL: xxx
Number of Quests: 3
App Store Reviews: App Store (Apple), Play Store (Android)
Buzz Content: Youtube, Instagram
```

- [x] Delete the preview tab

**Comment by ggomaeng** [comment]
Will be deployed after internationalization.
