### ISSUE TITLE
Quest status message

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#292]
![image](https://user-images.githubusercontent.com/1332279/66018545-81bbf500-e51a-11e9-864d-66cd09abca05.png)

`[]` should be removed

Also a user reported he saw a message:
"Your content [] was submitted, and it’s waiting for moderation."
even if the quest status was actually "joined" and there was no submission

**Comment by ggomaeng** [comment]
Should be fixed in #292
