### ISSUE TITLE
Duplicate campaign

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#298]

**Comment by sydneyitguy** [comment]
Now you can call  `/campaign/:id/duplicate.json` to duplicate all campaign and quests info.

**Comment by ggomaeng** [comment]
I will implement this after refactoring the maker profile code.

**Comment by ggomaeng** [comment]
Is this uploaded on postman documenter? What does the result return? @sydneyitguy
