### ISSUE TITLE
Crash during moderation

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#300]
Steps to reproduce:
1. Evaluate "other" content by putting follower and like counts, etc.
2. Approve or reject the content
3. Screen goes blank

and error message on the console:

![image](https://user-images.githubusercontent.com/1332279/67662136-21e42d00-f9a6-11e9-9bb7-58638900ee86.png)

**Comment by ggomaeng** [comment]
Is it possible you return "updated_at" field for `/buzz_channels/:id.json` api? I pushed a temporary fix in 717061f0

**Comment by sydneyitguy** [comment]
temp fix should be enough
