### ISSUE TITLE
Product Hunt referrals

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#302]
Design is on Zeplin `ph-main`

Criteria
- [x] Hide cat image from the banner on mobiles 
- [x] Catch URL parameter `?ref=producthunt` and if a maker signed up via the reference code, give 20% coupon code when they finish sign up.
=> When the parameter exists, send `referrer_id` as `1875`, I will handle others on the back-end
- [x] Add a sentence on Maker's confirmation email
```
This is the 20% discount coupon for Product Hunters. You can input this code when you run your review campaign. It will be expired in 30 days.
```

**Comment by cyh76507707** [comment]
Let's put this banner when we live the PH post.
![Screenshot 2019-10-30 14 48 23](https://user-images.githubusercontent.com/15100667/67868773-55e55c80-fb24-11e9-9ff4-d5cfdc6a51bd.png)

https://icons8.com/line-awesome?ref=producthunt

**Comment by ggomaeng** [comment]
How about we show the cat image like below for mobile? 

Desktop:

![image](https://user-images.githubusercontent.com/18402191/67897039-d3a46a80-fb1a-11e9-82c4-2b4441b455a1.png)

Mobile:

![image](https://user-images.githubusercontent.com/18402191/67897071-e28b1d00-fb1a-11e9-9b6c-378d4a35d7cc.png)

**Comment by ggomaeng** [comment]
I will temporarily set the default tabIndex for signup page to `TAB_MAKER` during this period.

**Comment by sydneyitguy** [comment]
@ggomaeng YH said "Hide cat image from the banner on mobiles"

Also, how about we pass `role?=maker` parameter on URL to choose which tab is selected by default?

**Comment by ggomaeng** [comment]
> @ggomaeng YH said "Hide cat image from the banner on mobiles"
> 
> Also, how about we pass `role?=maker` parameter on URL to choose which tab is selected by default?

Done.
