### ISSUE TITLE
Add referral bonus column

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#306]
Add generated bonus column on the referral table.
- Column 1: Total Reward --> Total amount of rewards that the referred hunters have gained so far since his/her signed-up
- Column 2: Referral Bonus --> Bonus amount I earned from this user

<img width="859" alt="Screenshot 2019-11-07 06 48 40" src="https://user-images.githubusercontent.com/15100667/68366204-a5cab180-012a-11ea-9150-0daf05ca48a2.png">

**Comment by sydneyitguy** [comment]
@ggomaeng Nice code: https://github.com/Steemhunt/reviewhunt-web/commit/e2061c9baa9ed470f0d7076f3c686021ccaff26f
It was very easy to modify 👍🏻

One thing, can you add comma separators on HUNT amount? (don't know how to do it 😂)

**Comment by ggomaeng** [comment]
Thanks :D should be fixed in 83b34c27. Can you double check though? I don't have enough referral data on my account to test.
