### ISSUE TITLE
Current step on campaign creation

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#31]
![image](https://user-images.githubusercontent.com/1332279/61844946-4c70a680-aedc-11e9-9be8-e8dfe0c77b55.png)

Two highlighted at the same time

**Comment by ggomaeng** [comment]
Should be fixed in https://github.com/Steemhunt/reviewhunt-web/commit/4135333680420a59a79a1d662caa3d41b2009224, but needs more testing.
