### ISSUE TITLE
Country filter for Maker

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#312]
- [ ] Interface on admin page

**Comment by ggomaeng** [comment]
@sydneyitguy API TODO:

- [ ] allowed_countries
- [ ] excluded_countries
- [ ] public

**Comment by sydneyitguy** [comment]
Changed attributes names:
- [ ] allowed_countries
- [ ] blocked_countries
- [ ] is_public

**Comment by sydneyitguy** [comment]
@ggomaeng I've updated the API, and also the front-end hiding logic.
Please add an admin interface, so makers (or admin) can update those parameters

**Comment by ggomaeng** [comment]
So if a campaign is "public", it means that anyone can join the campaign and it's visible to every country?

**Comment by sydneyitguy** [comment]
No. `is_public` flag is for the visibility.
allowed/blocked countries array is for the participation.

**Comment by ggomaeng** [comment]
Implemented in the old campaign draft form as well: 97ccdf84

![image](https://user-images.githubusercontent.com/18402191/69767466-3a746e00-1131-11ea-9911-66be22387a77.png)
