### ISSUE TITLE
User level

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#313]
Following fields will be added on
Hunter: `level`: integer starts from 0
Campaign: `min_level`: integer starts from 0

@ggomaeng 
If campaign.min_level > 0, that campaign is hidden publicly, and it should be visible to users who has higher level than that.

**Comment by ggomaeng** [comment]
Is this deployed in the staging api? I can't find the `level` field in the user object.

**Comment by sydneyitguy** [comment]
Close for country filter
