### ISSUE TITLE
Pre-fill text for review & buzz content

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#32]
e.g.

![image](https://user-images.githubusercontent.com/1332279/61845275-88f0d200-aedd-11e9-81b7-81238aeda34f.png)

We can just pre-fill those general text there, so makers can edit if they want
@cyh76507707 Please make some sentences there

**Comment by cyh76507707** [comment]
You can submit any review content with your own words via the following channels. However, please include the following items on your review content:
- Screenshots of you using the product
- Link of the product website or the app store link
