### ISSUE TITLE
Buzz max budget slide not showing

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#33]
![image](https://user-images.githubusercontent.com/1332279/61845347-d4a37b80-aedd-11e9-9201-d362bb5094d3.png)

I selected few buzz campaign channels, but the slider isn't showing (If fixes when I refresh the page and goes to the edit page)

**Comment by ggomaeng** [comment]
See #28 

https://github.com/Steemhunt/reviewhunt-web/issues/28#issuecomment-514914567
