### ISSUE TITLE
Campaign - special statuses

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#37]
These are all available statuses

```
draft submitted request_edit rejected paid refunded converting_hunt running distributing completed
```

![image](https://user-images.githubusercontent.com/1332279/61849186-6b2a6980-aeeb-11e9-9f6e-06c5ffeeb342.png)

1. Those menu items should only visible when the campaign status is `draft` or `request_edit`
2. When the maker clicks the "Submit for review" button on the last stage, change the campaign status to `submitted` (using PUT - /campaigns/:id.json API) and show payment information on the dashboard pannel
3. When status is `request_edit`, show the notification with `campaign.review_comment` and show the edit interfaces similar to `draft` 
4. When status is `rejected` or `refunded`, show the message with `campaign.review_comment` and makers cannot do any action.
5. When status is `paid` or `converting_hunt`, show a message like "Preparing your campaign..." and makers cannot do anything.
6. When status is `running`, show current moderation interface
7. When status is `distributing` or `completed`, show results and no actions.

API Changes:
https://github.com/Steemhunt/reviewhunt-api/commit/a7fbdea005d194fd62aef99be9eb9c6a376699ed

**Comment by ggomaeng** [comment]
Should be fixed in 08479b3a.

Payment options visible on "submitted"

![image](https://user-images.githubusercontent.com/18402191/61919857-72588280-af92-11e9-8c32-0dd48116e1a7.png)
