### ISSUE TITLE
Sign up page UI improvement

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#39]
1. Country selector - should be searchable
![image](https://user-images.githubusercontent.com/1332279/61855630-68377500-aefb-11e9-9275-7e5f50c6c0b2.png)

![image](https://user-images.githubusercontent.com/1332279/61855502-23134300-aefb-11e9-98de-ee473edf225c.png)
Let's use Ant Design has `Select search` field so user can search their country name instead of scroll down hundreds of lists (it's really annoying especially when there are multiple ways to write the country names - e.g. South Korea, Korea (Republic of), Republic of Korea, Korea, South...

2. Let's change gender selectors to capitalized form for consistency
![image](https://user-images.githubusercontent.com/1332279/61856603-6e2e5580-aefd-11e9-806a-737a6398dd86.png)

Male, Female, Other

3. DATE OF BIRTH => YEAR OF BIRTH
and probably InputNumber is better than a selector?

![image](https://user-images.githubusercontent.com/1332279/61857029-4e4b6180-aefe-11e9-94e8-0dd9ab523fd1.png)

**Comment by ggomaeng** [comment]
I think Selector for year of birth is fine as long as it has the search functionality.
