### ISSUE TITLE
Hunter dashboard - input design

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#40]
1. 
![image](https://user-images.githubusercontent.com/1332279/61857310-d7fb2f00-aefe-11e9-9152-4efe61432456.png)

![image](https://user-images.githubusercontent.com/1332279/61857736-aafb4c00-aeff-11e9-948f-4d7a0501693f.png)

I don't know why we use different styles for inputs on different pages, but those inputs with grey background and grey color looks very wrong because by convention:
 - grey background means "disabled" 
 - grey color text means "placeholder"

I think we can just use normal grey border box with white color background as same as maker's campaign form:

![image](https://user-images.githubusercontent.com/1332279/61857698-9b7c0300-aeff-11e9-857e-3e42fbf41867.png)

btw, change that select box bacgkround to white and grey bordered too.

**Comment by ggomaeng** [comment]
I second this opinion.

**Comment by cyh76507707** [comment]
Let's go for the second option.

**Comment by sydneyitguy** [comment]
There’s no second option... lol
Ok so we’ll just change all input style to white background and grey border one

**Comment by ggomaeng** [comment]
@sydneyitguy For the onboarding screen, I will maintain the same stylessheet. For the other input styles, I will change to white background with grey border.

![image](https://user-images.githubusercontent.com/18402191/61990199-c3da3d80-b076-11e9-85d7-2e7b2fd3f54e.png)

**Comment by sydneyitguy** [comment]
I guess just sign-up / signin  page style is better than that one @ggomaeng 

![image](https://user-images.githubusercontent.com/1332279/62002557-6fe85b00-b141-11e9-9c53-470d221afb10.png)

So only 2 styles for the inputs
1. Grey underline - on black background
2. Grey border - on white background
