### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#45]
Apply the text and design below (in Zeplin - `rh-email-confirm`).
![Screenshot 2019-07-25 11 47 26](https://user-images.githubusercontent.com/15100667/61868884-4675c800-aed2-11e9-8d9a-603a15e41c0a.png)

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/61919405-7aafbe00-af90-11e9-9e15-22d3acac89d0.png)

`VERIFY EMAIL` button should not be 100% width as it would look too wide on desktop. Responsive design (media query) cannot be applied using inline style, so I will just leave the button as normal. @cyh76507707
