### ISSUE TITLE
Connect Steem account

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#46]
![image](https://user-images.githubusercontent.com/1332279/61870948-76e15480-af1a-11e9-85c0-043cdcc938a8.png)

When connection succeed and callback, call `PATCH - /hunters/connect_steem.json` with `access_token`.

This will connect the Reviewhunt account to the Steem account and load all transaction data.

---

Oh and once it's connected, there's no going back (disconnect)
We should hide that section entirely, and let's just add one row on the profile section like:

STEEM ACCOUNT: (profile image) `@tabris`

I added `steem_username` on `/hunters/me.json` API.

**Comment by ggomaeng** [comment]
When the API is called, I receive an error: `{"error":"undefined method `email' for nil:NilClass"}`
