### ISSUE TITLE
After quest 1 submission

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#48]
![image](https://user-images.githubusercontent.com/1332279/61872412-31268b00-af1e-11e9-9e8f-7c798c3e9d58.png)

"Your content - [URL] was submitted..."

Sentence is weird, and it doesn't go to the next quest until it's refreshed.

If you meant to make those [URL] with actual content url and linked, please use 
`target="_blank" rel="noopener noreferrer"` options too.
(ref: https://github.com/tasti/react-linkify/pull/51)

**Comment by ggomaeng** [comment]
This was not implemented yet. However, now that I look at this, I think [URL] is only applicable to **Buzz Quest Submissions**. For all other submissions (General and Review), I will show this sentence -- "Your content was submitted, and it's waiting for moderation"
