### ISSUE TITLE
Screenshot example is missing

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#49]
On Hunter's quest dashboard

![image](https://user-images.githubusercontent.com/1332279/61872542-924e5e80-af1e-11e9-8ca4-745d26429239.png)

screenshot example is missing

and when a hunter submit the quest, proof image goes to the example 

![image](https://user-images.githubusercontent.com/1332279/61930203-10127880-afb8-11e9-9148-325a98a0c63b.png)

I think that proof image should have a separate section right to the screenshot example.

**Comment by ggomaeng** [comment]
The quest items in GET /campaigns/mine.json API should return image field. After that, it should render properly.
