### ISSUE TITLE
Paddings and alignment on Campaign list

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#5]
![image](https://user-images.githubusercontent.com/1332279/61689379-07286980-ad62-11e9-8229-f3832a32ead4.png)

It doesn't represent the hierarchy properly, and margin/padding should be fixed.
Please give @ggomaeng detailed guides there @cyh76507707

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/61691263-21644680-ad66-11e9-8543-000ae55e4126.png)

Maybe we can use Mac's Mail app tree style

**Comment by ggomaeng** [comment]
That looks good with me. The only concern I have is showing this format on mobile devices. Thoughts @cyh76507707?
