### ISSUE TITLE
About - mobile view

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#53]
![Mobile](https://user-images.githubusercontent.com/15100667/61876710-6bc00180-aee5-11e9-926a-42f83e92c499.jpg)
Same format below that part too.

**Comment by sydneyitguy** [comment]
image width should be 340px fixed, it should be % value depending on screen sizes.

**Comment by ggomaeng** [comment]
Tiny
![image](https://user-images.githubusercontent.com/18402191/62116191-b631eb80-b2f4-11e9-8aa9-a1d224d15656.png)

Mobile
![image](https://user-images.githubusercontent.com/18402191/62116331-f5f8d300-b2f4-11e9-80dd-49eac40bec62.png)

Tablet
![image](https://user-images.githubusercontent.com/18402191/62116360-027d2b80-b2f5-11e9-921c-949d42792b7e.png)
