### ISSUE TITLE
Dashboard Nav - Mobile view

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#56]
![dashboard-mobile](https://user-images.githubusercontent.com/15100667/61910532-dc3e4100-af2c-11e9-8037-4061c7fd5a9e.jpg)
- 네비 메뉴바 추가 (아이콘 + 메뉴타이틀)
- Earned, Next Get 태그 없애고 심플한 텍스트로

![dashboard-mobile-m1](https://user-images.githubusercontent.com/15100667/61910649-1f001900-af2d-11e9-829a-80bcf1bfd744.jpg)
- 헌터 대시보드 네비 메뉴 클릭했을 때

![dashboard-mobile-m2](https://user-images.githubusercontent.com/15100667/61910667-2aebdb00-af2d-11e9-9fee-28a6fa06ccbb.jpg)
- 메이커 대시보드 네비 메뉴 클릭했을 때

**Comment by ggomaeng** [comment]
Implemented in 07c6d8ac

![image](https://user-images.githubusercontent.com/18402191/63669072-ff9e2980-c813-11e9-8015-0768ac1d4c7b.png)
