### ISSUE TITLE
Unjoin campaign

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#61]
![image](https://user-images.githubusercontent.com/1332279/61935427-76ea5e80-afc5-11e9-89e2-09598c95971e.png)

front-end was calling unjoin API when it clicks the button again, so I implemented API and it's working now - https://github.com/Steemhunt/reviewhunt-api/commit/2c876b3d62f0f7e42658c1469a1cb126a61d819a

However, clicking the button "JOINED" to unjoin is little bit wrong (also it should only be possible when hunter hasn't joined on any quests)

Let's just put that "JOINED" button disabled when hunter's joined on that campaign,
and let's put "UNJOIN" button next to the CHECK PRODUCT INFO button on the quest dashboard => that way we can check whether hunter has already started a quest or not.

![image](https://user-images.githubusercontent.com/1332279/61935737-1a3b7380-afc6-11e9-848d-d8bc10a9de68.png)

We can use following style for UNJOIN button I guess
![image](https://user-images.githubusercontent.com/1332279/61935845-4eaf2f80-afc6-11e9-9814-1baebc960c66.png)

**Comment by sydneyitguy** [comment]
Please "disable" the JOINED button once it's joined

**Comment by ggomaeng** [comment]
Fixed in e8fdfbb9

**Comment by cyh76507707** [comment]
Please add a text button below the joined button like this:

`Go to Quest Dashboard >`

Also the same button below the guidelines too.
(So two buttons on top and bottom so that a user can go to the quest dashboard easily.)

**Comment by ggomaeng** [comment]
@cyh76507707 Right now, the user is redirected to Quest Dashboard right after they join the quest. Also, after they join the quest, the bottom join button is hidden.

![image](https://user-images.githubusercontent.com/18402191/62047332-2da84200-b245-11e9-8ca8-316668e4fd11.png)

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/62279680-849c5a00-b485-11e9-8804-00dec6bdea90.png)
Once hunter has joined on a campaign, I think we can just replace that button to "Go to Quest Dashboard"
