### ISSUE TITLE
Next steps should be disabled when campaign budget not set

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#62]
![image](https://user-images.githubusercontent.com/1332279/61937322-908da500-afc9-11e9-9dcd-3b8a59c541bd.png)

Next steps should be disabled when campaign budget not set
Otherwise, when I click the payment option, it will show "amount cannot be 0" error

**Comment by ggomaeng** [comment]
Fixed in 57d82837
