### ISSUE TITLE
Buzz submission - image is optional

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#68]
Image is optional for buzz quests

![image](https://user-images.githubusercontent.com/1332279/61951218-51704b80-afeb-11e9-95eb-ac204f0b6534.png)

**Comment by ggomaeng** [comment]
I tried submitting a buzz quest without an image and received this error:
```
{"error":"Proof image can't be blank"}
```

![image](https://user-images.githubusercontent.com/18402191/61962211-00b91c80-b004-11e9-847f-308a9e634c2b.png)

**Comment by sydneyitguy** [comment]
Oh I remembered we discussed this before, and decided to made the image field compulsory for every quest.

Please just removed "(Optional)" text on the description then @ggomaeng
