### ISSUE TITLE
Let's add bounty amount there

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#70]
![image](https://user-images.githubusercontent.com/1332279/61952784-c34a9400-afef-11e9-8084-83b5437d2a6e.png)

As we made the general quest bounty amount customizable, let's show the amount (in USD) on that

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/61961730-fba79d80-b002-11e9-9b53-cf5c21c4d261.png)
