### ISSUE TITLE
Quest creation steps

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#8]
<Steps>
1. Add general quest 3 without saving quest 2
2. Then click the save button on quest 2

I get following error on console and nothing happens:

![image](https://user-images.githubusercontent.com/1332279/61758124-72277e00-adfe-11e9-9292-dbd22722f370.png)

**Comment by ggomaeng** [comment]
Should be fixed in https://github.com/Steemhunt/reviewhunt-web/commit/0ce050c8128fdc1724344fd38519a02a1e419ada#diff-ef2e857e14d10aa74207530454df0943R286

**Comment by ggomaeng** [comment]
Please reopen the issue if you can reproduce the error.
