### ISSUE TITLE
Submitted campaigns

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#86]
![image](https://user-images.githubusercontent.com/1332279/61995466-ec3c5900-b0c3-11e9-9445-8cce93c578cc.png)

I just submitted a campaigns, but it didn't replace that "SCREENSHOT EXAMPLE" section to my submission

**Comment by ggomaeng** [comment]
The preview only shows for General quests now, because
1) Review submissions will look identical to the proof example
2) Buzz quest submissions have a different design
