### ISSUE TITLE
Buzz quest reward cap

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#90]
![image](https://user-images.githubusercontent.com/1332279/61995732-38d56380-b0c7-11e9-8ab4-a25ad79a4136.png)

bounty_max cap is applied on hunter side correctly

![image](https://user-images.githubusercontent.com/1332279/61995724-14798700-b0c7-11e9-9473-8c63cb96bf6e.png)

but not on maker's moderation interface

**Comment by ggomaeng** [comment]
Duplicate #82
