### ISSUE TITLE
Update `bounty_left` after review

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#92]
Now `hunter_quests/:id/review.json` API will return the updated status of campaign.

```json
"campaign": {
        "current_participant_count": 3,
        "total_bounty": "5000.0",
        "bounty_left": "3277.948",
        "status": "running",
        "updated_at": "2019-07-27T15:01:10.662Z"
    }
```

Please merge this info after a maker reviewed a submission

**Comment by ggomaeng** [comment]
Can you rename the "status" field? It clashes with the "status" field of the submitted item.

**Comment by ggomaeng** [comment]
The bounty_left field returns the same value after reviewing

![image](https://user-images.githubusercontent.com/18402191/62003321-7b8f4e00-b150-11e9-88fe-ead616df7f62.png)
