### ISSUE TITLE
Menu list is missing on the Setting page

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#93]
This is a view of Maker's dashboard. The menu lists are suddenly missed.
**Also, please add a `cancel` button too.**
![Screenshot 2019-07-27 16 44 21](https://user-images.githubusercontent.com/15100667/61996640-4d493a00-b08e-11e9-8ea9-f0dd08894718.png)

**Comment by ggomaeng** [comment]
1. Do you have ongoing campaigns? The campaigns tab is not visible when there are no campaigns running.

2. The create campaign list is only visible when you click on "Create Campaign" button.

3. Cancel button is visible after you click on "Edit Profile"
