### ISSUE TITLE
Terms & Privacy

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#95]
Terms: https://docs.google.com/document/d/1EhQBAt96j8-2vGfkxwSQj1-iF5a5QdbQ7_2Vn7t1DZg/edit

Privacy: https://docs.google.com/document/d/1i6A7CVioPLLcF_3xYJ0MjncPimw-KoCP8AkxsWi_TOQ/edit#heading=h.htp9tlcuq0q5

**Comment by cyh76507707** [comment]
Cookie: https://docs.google.com/document/d/17YhD7rTfuT9xf_6SOFssdFT8FBhQi5Vyio-W2ObUja4/edit?usp=sharing

All of the docs still under copy editing works. Will share as `.html` files as soon it's ready.
