### ISSUE TITLE
Saved quest description has gone all of sudden.

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#97]
When I click the save and next button after I filled in the last quest field, all of sudden there's a loading icon is appeared on the prev quest (that are already saved previously), and nothing happened for a while.
![Screenshot 2019-07-27 17 12 02](https://user-images.githubusercontent.com/15100667/61996916-05c4ad00-b092-11e9-8604-03e24d1e4c4b.png)

So, I refreshed the page, and the Quest 2 content has gone all of sudden, and the Quest 3 content has moved to Quest 2 section.

**Comment by cyh76507707** [comment]
Another related bug.
When I tried to delete the Quest 2 (because I need to add the original Quest 2 that were missed), it shows the `user not found` alert and I can't delete it.

![bug-1](https://user-images.githubusercontent.com/15100667/61997026-3822da00-b093-11e9-9a1d-9d44cfe9a821.gif)

**Comment by ggomaeng** [comment]
I just fixed the quest delete bug. Still investigating the save bug.

**Comment by sydneyitguy** [comment]
Please create a new ticket if this bug still exists
