### ISSUE TITLE
[Login - Maker] Change the alert when they tried on Hunter's tab

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#99]
Please change the alert message as below:
`There isn’t a Hunter account associated with this email address. Please try another email, or make sure you're trying to log in as a Hunter.`

![Screenshot 2019-07-27 17 41 39](https://user-images.githubusercontent.com/15100667/61997207-3f97b280-b096-11e9-9942-77878af48729.png)

**Comment by sydneyitguy** [comment]
@cyh76507707 Now you can edit this sentence on https://github.com/Steemhunt/reviewhunt-web/blob/master/public/locales/en/translation.json

Oh but this error code is the same for both hunter and maker login.
I will add two separate messages for that
